### ISSUE TITLE
TypeError: log_posterior() got an unexpected keyword argument 'flux_init'

### ISSUE THREAD

**Issue by sureshparekh** [astrostat/pylira#64]
Hi @adonath ,
When I try to run [Introduction to Deconvolution using MCMC Methods Tutorial](https://pylira.readthedocs.io/en/latest/pylira/user/tutorials/notebooks/mcmc-deconvolution-intro.html), I am getting a type error as mentioned below in the 43rd cell which linked to cell 39.

```bash
TypeError                                 Traceback (most recent call last)
File :5

Cell In[39], line 13, in deconvolve_mcmc(log_posterior, flux_init, data, n_samples, flux_min)
     10 while len(image_trace) < n_samples:
     11     flux = rng.gamma(np.clip(flux_init, flux_min, np.inf))
---> 13     prob = log_posterior(flux=flux, **data)
     14     prob_init = log_posterior(flux=flux_init, **data)
     16     acceptance = min(np.exp(prob_init - prob), 1)

TypeError: log_posterior() got an unexpected keyword argument 'flux_init'
```

Please help me resolve this issue.

Also, I found that the GitHub code and the code installed by pip don't match. I installed pylira using pip, and it created an error when I tried to run the tutorials. When I checked both the codes of core.py and _init_.py, they differed, which caused the error. I request the developers to update the library on the pip server too. 

Thanks!
![Screenshot from 2023-04-04 18-26-10](https://user-images.githubusercontent.com/53847845/229801496-128ec0e0-4d64-4b65-8ee8-ab52c7f9fe17.png)

**Comment by adonath** [comment]
Thanks for opening the issue @sureshparekh! 

In your specific case it seems the `data` dict contains the `flux_init` keyword (you must have added it earlier in the notebo). The error should be resolved once you remove it again e.g. like:

```python3
data.pop("flux_init", None)
```

Note in this tutorial the `data` dict is handled slightly differently than in the "normal" Pylira `Deconvolver` class, which requires the `flux_init` keyword to present. I hope this answers your question!

**Comment by adonath** [comment]
> Also, I found that the GitHub code and the code installed by pip don't match. I installed pylira using pip, and it created an error when I tried to run the tutorials. When I checked both the codes of core.py and init.py, they differed, which caused the error. I request the developers to update the library on the pip server too.

Yes, we will make a new release including some new features and bug-fixes soon.

**Comment by sureshparekh** [comment]
> Thanks for opening the issue @sureshparekh!
> 
> In your specific case it seems the `data` dict contains the `flux_init` keyword (you must have added it earlier in the notebo). The error should be resolved once you remove it again e.g. like:
> 
> ```python
> data.pop("flux_init", None)
> ```
> 
> Note in this tutorial the `data` dict is handled slightly differently than in the "normal" Pylira `Deconvolver` class, which requires the `flux_init` keyword to present. I hope this answers your question!

Thanks a lot for the reply. Yes I figured out the issue as per your suggestion.

**Comment by sureshparekh** [comment]
@adonath 
I need some help using pylira. Can I contact you via email?
